import { Character } from "./Character";

export const Andy: Character = {
  name: "Andy",
  textures: {
    head: "andyHead",
    leftArm: "andyLeftArm",
    leftHand: "andyLeftHand",
    rightArm: "andyRightArm",
    rightHand: "andyRightHand",
    torso: "andyTorso",
  },

  sounds: {
    death: ["andyDeath1", "andyDeath2", "andyDeath3", "andyDeath4"],
    hurt: [
      "andyHurt1",
      "andyHurt2",
      "andyHurt3",
      "andyHurt4",
      "andyHurt5",
      "andyHurt6",
      "andyHurt7",
      "andyHurt8",
    ],
    joinParty: ["andyJoinParty1", "andyJoinParty2", "andyJoinParty3"],
    lookHere: ["andyLookHere1", "andyLookHere2"],
    misc: ["andyMisc1", "andyMisc2", "andyMisc3"],
    nearDeath: [
      "andyNearDeath1",
      "andyNearDeath2",
      "andyNearDeath3",
      "andyNearDeath4",
    ],
    newLevel: ["andyNewLevel1", "andyNewLevel2"],
    pickupItem: [
      "andyPickup1",
      "andyPickup2",
      "andyPickup3",
      "andyPickup4",
      "andyPickup5",
    ],
    pickupGun: [
      "andyPickup1",
      "andyPickup2",
      "andyPickup3",
      "andyPickup4",
      "andyPickup5",
    ],
    pickupMelee: [
      "andyPickup1",
      "andyPickup2",
      "andyPickup3",
      "andyPickup4",
      "andyPickup5",
    ],
    pickupHealth: [
      "andyPickup1",
      "andyPickup2",
      "andyPickup3",
      "andyPickup4",
      "andyPickup5",
    ],
    relief: [
      "andyRelief1",
      "andyRelief2",
      "andyRelief3",
      "andyRelief4",
      "andyRelief5",
      "andyRelief6",
    ],
    taunts: ["andyTaunt1", "andyTaunt2"],
    worried: [
      "andyWorried1",
      "andyWorried2",
      "andyWorried3",
      "andyWorried4",
      "andyWorried5",
    ],
  },
};
