import { Character } from "./Character";

export const DustyRusty: Character = {
  name: "Dusty Rusty",
  textures: {
    head: "dustyRustyHead",
    leftArm: "dustyRustyLeftArm",
    leftHand: "dustyRustyLeftHand",
    rightArm: "dustyRustyRightArm",
    rightHand: "dustyRustyRightHand",
    torso: "dustyRustyTorso",
  },

  sounds: {
    death: ["dustyRustyDeath1", "dustyRustyDeath2"],
    hurt: [
      "dustyRustyHurt1",
      "dustyRustyHurt2",
      "dustyRustyHurt3",
      "dustyRustyHurt4",
      "dustyRustyHurt5",
      "dustyRustyHurt6",
      "dustyRustyHurt7",
      "dustyRustyHurt8",
      "dustyRustyHurt9",
      "dustyRustyHurt10",
    ],
    joinParty: ["dustyRustyJoinParty1", "dustyRustyJoinParty2"],
    lookHere: [
      "dustyRustyLookHere1",
      "dustyRustyLookHere2",
      "dustyRustyLookHere3",
      "dustyRustyLookHere4",
    ],
    misc: [
      "dustyRustyMisc1",
      "dustyRustyMisc2",
      "dustyRustyMisc3",
      "dustyRustyMisc4",
    ],
    nearDeath: ["dustyRustyNearDeath1", "dustyRustyNearDeath2"],
    newLevel: [
      "dustyRustyNewLevel1",
      "dustyRustyNewLevel2",
      "dustyRustyNewLevel3",
      "dustyRustyNewLevel4",
      "dustyRustyNewLevel5",
      "dustyRustyNewLevel6",
      "dustyRustyNewLevel7",
      "dustyRustyNewLevel8",
      "dustyRustyNewLevel9",
      "dustyRustyNewLevel10",
      "dustyRustyNewLevel11",
      "dustyRustyNewLevel12",
    ],
    pickupItem: [],
    pickupGun: [
      "dustyRustyPickup1",
      "dustyRustyPickup3",
      "dustyRustyPickup4",
      "dustyRustyPickup6",
      "dustyRustyPickup7",
      "dustyRustyPickup8",
    ],
    pickupMelee: ["dustyRustyPickup2", "dustyRustyPickup5"],
    pickupHealth: [
      "dustyRustyPickup9Health",
      "dustyRustyPickup10Health",
      "dustyRustyPickup11Health",
    ],
    relief: [
      "dustyRustyLevelComplete1",
      "dustyRustyLevelComplete2",
      "dustyRustyLevelComplete3",
      "dustyRustyLevelComplete4",
      "dustyRustyLevelComplete5",
    ],
    taunts: [
      "dustyRustyTaunt1",
      "dustyRustyTaunt2",
      "dustyRustyTaunt3",
      "dustyRustyTaunt4",
      "dustyRustyTaunt5",
      "dustyRustyTaunt6",
      "dustyRustyTaunt7",
      "dustyRustyTaunt8",
    ],
    worried: [
      "dustyRustyWorried1",
      "dustyRustyWorried2",
      "dustyRustyWorried3",
      "dustyRustyWorried4",
      "dustyRustyWorried5",
      "dustyRustyWorried6",
    ],
  },
};
