// This file is autogenerated by bin/generate-manifest.ts
// Do not modify it by hand. Any changes will be overwritten.
import images0 from "./images/characters/andy-head.png?url";
import images1 from "./images/characters/andy-left-arm.png?url";
import images2 from "./images/characters/andy-left-hand.png?url";
import images3 from "./images/characters/andy-right-arm.png?url";
import images4 from "./images/characters/andy-right-hand.png?url";
import images5 from "./images/characters/andy-torso.png?url";
import images6 from "./images/characters/chad-head.png?url";
import images7 from "./images/characters/chad-left-arm.png?url";
import images8 from "./images/characters/chad-left-hand.png?url";
import images9 from "./images/characters/chad-right-arm.png?url";
import images10 from "./images/characters/chad-right-hand.png?url";
import images11 from "./images/characters/chad-torso.png?url";
import images12 from "./images/characters/cindy-head.png?url";
import images13 from "./images/characters/cindy-left-arm.png?url";
import images14 from "./images/characters/cindy-left-hand.png?url";
import images15 from "./images/characters/cindy-right-arm.png?url";
import images16 from "./images/characters/cindy-right-hand.png?url";
import images17 from "./images/characters/cindy-torso.png?url";
import images18 from "./images/characters/clarice-head.png?url";
import images19 from "./images/characters/clarice-left-arm.png?url";
import images20 from "./images/characters/clarice-left-hand.png?url";
import images21 from "./images/characters/clarice-right-arm.png?url";
import images22 from "./images/characters/clarice-right-hand.png?url";
import images23 from "./images/characters/clarice-torso.png?url";
import images24 from "./images/characters/dusty-rusty-head.png?url";
import images25 from "./images/characters/dusty-rusty-left-arm.png?url";
import images26 from "./images/characters/dusty-rusty-left-hand.png?url";
import images27 from "./images/characters/dusty-rusty-right-arm.png?url";
import images28 from "./images/characters/dusty-rusty-right-hand.png?url";
import images29 from "./images/characters/dusty-rusty-torso.png?url";
import images30 from "./images/characters/kyle-head.png?url";
import images31 from "./images/characters/kyle-left-arm.png?url";
import images32 from "./images/characters/kyle-left-hand.png?url";
import images33 from "./images/characters/kyle-right-arm.png?url";
import images34 from "./images/characters/kyle-right-hand.png?url";
import images35 from "./images/characters/kyle-torso.png?url";
import images36 from "./images/characters/lucky-jack-head.png?url";
import images37 from "./images/characters/lucky-jack-left-arm.png?url";
import images38 from "./images/characters/lucky-jack-left-hand.png?url";
import images39 from "./images/characters/lucky-jack-right-arm.png?url";
import images40 from "./images/characters/lucky-jack-right-hand.png?url";
import images41 from "./images/characters/lucky-jack-torso.png?url";
import images42 from "./images/characters/mike-head.png?url";
import images43 from "./images/characters/mike-left-arm.png?url";
import images44 from "./images/characters/mike-left-hand.png?url";
import images45 from "./images/characters/mike-right-arm.png?url";
import images46 from "./images/characters/mike-right-hand.png?url";
import images47 from "./images/characters/mike-torso.png?url";
import images48 from "./images/characters/nancy-head.png?url";
import images49 from "./images/characters/nancy-left-arm.png?url";
import images50 from "./images/characters/nancy-left-hand.png?url";
import images51 from "./images/characters/nancy-right-arm.png?url";
import images52 from "./images/characters/nancy-right-hand.png?url";
import images53 from "./images/characters/nancy-torso.png?url";
import images54 from "./images/characters/santa-head.png?url";
import images55 from "./images/characters/santa-left-arm.png?url";
import images56 from "./images/characters/santa-left-hand.png?url";
import images57 from "./images/characters/santa-right-arm.png?url";
import images58 from "./images/characters/santa-right-hand.png?url";
import images59 from "./images/characters/santa-torso.png?url";
import images60 from "./images/characters/simon-head.png?url";
import images61 from "./images/characters/simon-left-arm.png?url";
import images62 from "./images/characters/simon-left-hand.png?url";
import images63 from "./images/characters/simon-right-arm.png?url";
import images64 from "./images/characters/simon-right-hand.png?url";
import images65 from "./images/characters/simon-torso.png?url";
import images66 from "./images/characters/takeshi-head.png?url";
import images67 from "./images/characters/takeshi-left-arm.png?url";
import images68 from "./images/characters/takeshi-left-hand.png?url";
import images69 from "./images/characters/takeshi-right-arm.png?url";
import images70 from "./images/characters/takeshi-right-hand.png?url";
import images71 from "./images/characters/takeshi-torso.png?url";
import images72 from "./images/characters/wendy-head.png?url";
import images73 from "./images/characters/wendy-left-arm.png?url";
import images74 from "./images/characters/wendy-left-hand.png?url";
import images75 from "./images/characters/wendy-right-arm.png?url";
import images76 from "./images/characters/wendy-right-hand.png?url";
import images77 from "./images/characters/wendy-torso.png?url";
import images78 from "./images/effects/glow-stick-1.png?url";
import images79 from "./images/effects/glow-stick-2.png?url";
import images80 from "./images/effects/glow-stick-3.png?url";
import images81 from "./images/effects/health-overlay.png?url";
import images82 from "./images/effects/impact-particle.png?url";
import images83 from "./images/environment/bathroom.png?url";
import images84 from "./images/environment/bathroom/sink-1.png?url";
import images85 from "./images/environment/bathroom/sink-3.png?url";
import images86 from "./images/environment/bathroom/sink-group-1.png?url";
import images87 from "./images/environment/bathroom/sink-group-2.png?url";
import images88 from "./images/environment/bathroom/sink-group-3.png?url";
import images89 from "./images/environment/bathroom/sink-group-4.png?url";
import images90 from "./images/environment/bathroom/sink-group-5.png?url";
import images91 from "./images/environment/bathroom/sink-group-6.png?url";
import images92 from "./images/environment/bathroom/sink2.png?url";
import images93 from "./images/environment/bathroom/toilet-1.png?url";
import images94 from "./images/environment/bathroom/toilet-2.png?url";
import images95 from "./images/environment/bathroom/toilet-3.png?url";
import images96 from "./images/environment/bathroom/toilet-4.png?url";
import images97 from "./images/environment/bathroom/toilet-5.png?url";
import images98 from "./images/environment/bookcase-1.png?url";
import images99 from "./images/environment/bookcase-2.png?url";
import images100 from "./images/environment/box-pile-1.png?url";
import images101 from "./images/environment/box-pile-2.png?url";
import images102 from "./images/environment/box-shelf-1.png?url";
import images103 from "./images/environment/box-shelf-2.png?url";
import images104 from "./images/environment/chain-link-fence.png?url";
import images105 from "./images/environment/doors/door-1.png?url";
import images106 from "./images/environment/doors/door-2.png?url";
import images107 from "./images/environment/fancy-furniture.png?url";
import images108 from "./images/environment/fancy-rug-1.png?url";
import images109 from "./images/environment/fence.png?url";
import images110 from "./images/environment/floor/IndustrialCarpet-001.jpg?url";
import images111 from "./images/environment/floor/IndustrialCarpet-002.jpg?url";
import images112 from "./images/environment/floor/bathroom-tile-floor-1.png?url";
import images113 from "./images/environment/floor/bathroom-tile-floor-2.png?url";
import images114 from "./images/environment/floor/bathroom-tile-floor-3.png?url";
import images115 from "./images/environment/floor/bathroom-tile-floor-4.png?url";
import images116 from "./images/environment/floor/carpet.png?url";
import images117 from "./images/environment/floor/cement.png?url";
import images118 from "./images/environment/floor/granite-1.jpg?url";
import images119 from "./images/environment/floor/granite-2.jpg?url";
import images120 from "./images/environment/floor/granite-3.jpg?url";
import images121 from "./images/environment/floor/marble-1.jpg?url";
import images122 from "./images/environment/floor/old-plank-flooring-1.png?url";
import images123 from "./images/environment/floor/old-plank-flooring-2.png?url";
import images124 from "./images/environment/floor/steel-floor.png?url";
import images125 from "./images/environment/floor/tile-floor-1.png?url";
import images126 from "./images/environment/floor/tile-floor-10.jpg?url";
import images127 from "./images/environment/floor/tile-floor-11.jpg?url";
import images128 from "./images/environment/floor/tile-floor-12.jpg?url";
import images129 from "./images/environment/floor/tile-floor-13.jpg?url";
import images130 from "./images/environment/floor/tile-floor-14.jpg?url";
import images131 from "./images/environment/floor/tile-floor-15.jpg?url";
import images132 from "./images/environment/floor/tile-floor-2.png?url";
import images133 from "./images/environment/floor/tile-floor-3.png?url";
import images134 from "./images/environment/floor/tile-floor-4.png?url";
import images135 from "./images/environment/floor/tile-floor-5.png?url";
import images136 from "./images/environment/floor/tile-floor-6.png?url";
import images137 from "./images/environment/floor/tile-floor-7.png?url";
import images138 from "./images/environment/floor/tile-floor-8.png?url";
import images139 from "./images/environment/floor/tile-floor-9.jpg?url";
import images140 from "./images/environment/floor/wood-floor-1.png?url";
import images141 from "./images/environment/floor/wood-floor-2.png?url";
import images142 from "./images/environment/floor/wood-floor-3.png?url";
import images143 from "./images/environment/floor/wooden-floor.png?url";
import images144 from "./images/environment/furniture.png?url";
import images145 from "./images/environment/furniture/fancy-chair-1.png?url";
import images146 from "./images/environment/furniture/fancy-end-table-1.png?url";
import images147 from "./images/environment/furniture/fancy-end-table-2.png?url";
import images148 from "./images/environment/furniture/fancy-table-1.png?url";
import images149 from "./images/environment/furniture/fancy-table-2.png?url";
import images150 from "./images/environment/furniture/lobby-desk-1.png?url";
import images151 from "./images/environment/furniture/piano.png?url";
import images152 from "./images/environment/maintenance/transformer.png?url";
import images153 from "./images/environment/shops/shelf-1.png?url";
import images154 from "./images/environment/shops/shop-counter-1.png?url";
import images155 from "./images/environment/shops/shop-counter-2.png?url";
import images156 from "./images/environment/shops/shop-counter-3.png?url";
import images157 from "./images/environment/stairs.png?url";
import images158 from "./images/environment/vending-machines/vending-machine-1.png?url";
import images159 from "./images/environment/vending-machines/vending-machine-2.png?url";
import images160 from "./images/environment/vending-machines/vending-machine-3.png?url";
import images161 from "./images/environment/vending-machines/vending-machine-glow-1.png?url";
import images162 from "./images/environment/vending-machines/vending-machine-glow-2.png?url";
import images163 from "./images/environment/vending-machines/vending-machine-glow-3.png?url";
import images164 from "./images/environment/wall-1.png?url";
import images165 from "./images/environment/water-cooler.png?url";
import images166 from "./images/favicon.png?url";
import images167 from "./images/health-kit.png?url";
import images168 from "./images/lights/point-light.png?url";
import images169 from "./images/muzzle_flashs/muzzle-flash-1.png?url";
import images170 from "./images/muzzle_flashs/muzzle-flash-10.png?url";
import images171 from "./images/muzzle_flashs/muzzle-flash-11.png?url";
import images172 from "./images/muzzle_flashs/muzzle-flash-12.png?url";
import images173 from "./images/muzzle_flashs/muzzle-flash-13.png?url";
import images174 from "./images/muzzle_flashs/muzzle-flash-14.png?url";
import images175 from "./images/muzzle_flashs/muzzle-flash-15.png?url";
import images176 from "./images/muzzle_flashs/muzzle-flash-16.png?url";
import images177 from "./images/muzzle_flashs/muzzle-flash-2.png?url";
import images178 from "./images/muzzle_flashs/muzzle-flash-3.png?url";
import images179 from "./images/muzzle_flashs/muzzle-flash-4.png?url";
import images180 from "./images/muzzle_flashs/muzzle-flash-5.png?url";
import images181 from "./images/muzzle_flashs/muzzle-flash-6.png?url";
import images182 from "./images/muzzle_flashs/muzzle-flash-7.png?url";
import images183 from "./images/muzzle_flashs/muzzle-flash-8.png?url";
import images184 from "./images/muzzle_flashs/muzzle-flash-9.png?url";
import images185 from "./images/shell-casings/pistol-casing.png?url";
import images186 from "./images/shell-casings/rifle-casing.png?url";
import images187 from "./images/shell-casings/shotgun-casing.png?url";
import images188 from "./images/solid-circle.png?url";
import images189 from "./images/splats/blob-1.png?url";
import images190 from "./images/splats/blob-2.png?url";
import images191 from "./images/splats/blob-3.png?url";
import images192 from "./images/splats/blob-4.png?url";
import images193 from "./images/splats/blob-5.png?url";
import images194 from "./images/splats/blob-glow-1.png?url";
import images195 from "./images/splats/blob-glow-2.png?url";
import images196 from "./images/splats/blob-glow-3.png?url";
import images197 from "./images/splats/blob-glow-4.png?url";
import images198 from "./images/splats/blob-glow-5.png?url";
import images199 from "./images/splats/splat-glow_1.png?url";
import images200 from "./images/splats/splat-glow_2.png?url";
import images201 from "./images/splats/splat-glow_3.png?url";
import images202 from "./images/splats/splat-glow_4.png?url";
import images203 from "./images/splats/splat-glow_5.png?url";
import images204 from "./images/splats/splat-glow_6.png?url";
import images205 from "./images/splats/splat-glow_7.png?url";
import images206 from "./images/splats/splat_1.png?url";
import images207 from "./images/splats/splat_2.png?url";
import images208 from "./images/splats/splat_3.png?url";
import images209 from "./images/splats/splat_4.png?url";
import images210 from "./images/splats/splat_5.png?url";
import images211 from "./images/splats/splat_6.png?url";
import images212 from "./images/splats/splat_7.png?url";
import images213 from "./images/weapons/ak-47-hold.png?url";
import images214 from "./images/weapons/ak47-pickup.png?url";
import images215 from "./images/weapons/ar-15-pickup.png?url";
import images216 from "./images/weapons/ar15-hold.png?url";
import images217 from "./images/weapons/axe.png?url";
import images218 from "./images/weapons/baseball-bat-hold.png?url";
import images219 from "./images/weapons/baseball-bat-pickup.png?url";
import images220 from "./images/weapons/desert-eagle-hold.png?url";
import images221 from "./images/weapons/desert-eagle-pickup.png?url";
import images222 from "./images/weapons/double-barrel-shotgun-hold.png?url";
import images223 from "./images/weapons/double-barrel-shotgun-pickup.png?url";
import images224 from "./images/weapons/five-seven-hold.png?url";
import images225 from "./images/weapons/five-seven-pickup.png?url";
import images226 from "./images/weapons/glock-hold.png?url";
import images227 from "./images/weapons/glock-pickup.png?url";
import images228 from "./images/weapons/katana.png?url";
import images229 from "./images/weapons/magazines/ak-magazine.png?url";
import images230 from "./images/weapons/magazines/p90-magazine.png?url";
import images231 from "./images/weapons/magazines/pistol-magazine.png?url";
import images232 from "./images/weapons/magazines/revolver-round.png?url";
import images233 from "./images/weapons/magazines/rifle-magazine.png?url";
import images234 from "./images/weapons/magazines/shotgun-shell-pair.png?url";
import images235 from "./images/weapons/magazines/shotgun-shell.png?url";
import images236 from "./images/weapons/magnum-hold.png?url";
import images237 from "./images/weapons/magnum-pickup.png?url";
import images238 from "./images/weapons/p90-hold.png?url";
import images239 from "./images/weapons/p90-pickup.png?url";
import images240 from "./images/weapons/remington-870-hold.png?url";
import images241 from "./images/weapons/remington-pickup.png?url";
import images242 from "./images/weapons/spas12-hold.png?url";
import images243 from "./images/weapons/spas12-pickup.png?url";
import images244 from "./images/zombies/crawler-1.png?url";
import images245 from "./images/zombies/crawler-2.png?url";
import images246 from "./images/zombies/crawler-3.png?url";
import images247 from "./images/zombies/crawler-head-1.png?url";
import images248 from "./images/zombies/crawler-head-2.png?url";
import images249 from "./images/zombies/crawler-head-3.png?url";
import images250 from "./images/zombies/crawler-left-arm-1.png?url";
import images251 from "./images/zombies/crawler-left-arm-2.png?url";
import images252 from "./images/zombies/crawler-left-arm-3.png?url";
import images253 from "./images/zombies/crawler-left-hand-1.png?url";
import images254 from "./images/zombies/crawler-left-hand-2.png?url";
import images255 from "./images/zombies/crawler-left-hand-3.png?url";
import images256 from "./images/zombies/crawler-right-arm-1.png?url";
import images257 from "./images/zombies/crawler-right-arm-2.png?url";
import images258 from "./images/zombies/crawler-right-arm-3.png?url";
import images259 from "./images/zombies/crawler-right-hand-1.png?url";
import images260 from "./images/zombies/crawler-right-hand-2.png?url";
import images261 from "./images/zombies/crawler-right-hand-3.png?url";
import images262 from "./images/zombies/crawler-torso-1.png?url";
import images263 from "./images/zombies/crawler-torso-2.png?url";
import images264 from "./images/zombies/crawler-torso-3.png?url";
import images265 from "./images/zombies/crawler.png?url";
import images266 from "./images/zombies/heavy.png?url";
import images267 from "./images/zombies/necromancer.png?url";
import images268 from "./images/zombies/spitter.png?url";
import images269 from "./images/zombies/zombie-1.png?url";
import images270 from "./images/zombies/zombie-2.png?url";
import images271 from "./images/zombies/zombie-3.png?url";
import images272 from "./images/zombies/zombie-head-1.png?url";
import images273 from "./images/zombies/zombie-head-2.png?url";
import images274 from "./images/zombies/zombie-head-3.png?url";
import images275 from "./images/zombies/zombie-left-arm-1.png?url";
import images276 from "./images/zombies/zombie-left-arm-2.png?url";
import images277 from "./images/zombies/zombie-left-arm-3.png?url";
import images278 from "./images/zombies/zombie-left-hand-1.png?url";
import images279 from "./images/zombies/zombie-left-hand-2.png?url";
import images280 from "./images/zombies/zombie-left-hand-3.png?url";
import images281 from "./images/zombies/zombie-legs-1.png?url";
import images282 from "./images/zombies/zombie-legs-2.png?url";
import images283 from "./images/zombies/zombie-legs-3.png?url";
import images284 from "./images/zombies/zombie-right-arm-1.png?url";
import images285 from "./images/zombies/zombie-right-arm-2.png?url";
import images286 from "./images/zombies/zombie-right-arm-3.png?url";
import images287 from "./images/zombies/zombie-right-hand-1.png?url";
import images288 from "./images/zombies/zombie-right-hand-2.png?url";
import images289 from "./images/zombies/zombie-right-hand-3.png?url";
import images290 from "./images/zombies/zombie-torso-1.png?url";
import images291 from "./images/zombies/zombie-torso-2.png?url";
import images292 from "./images/zombies/zombie-torso-3.png?url";
import sounds0 from "./audio/characters/andy/andy-death-1.flac?url";
import sounds1 from "./audio/characters/andy/andy-death-2.flac?url";
import sounds2 from "./audio/characters/andy/andy-death-3.flac?url";
import sounds3 from "./audio/characters/andy/andy-death-4.flac?url";
import sounds4 from "./audio/characters/andy/andy-hurt-1.flac?url";
import sounds5 from "./audio/characters/andy/andy-hurt-2.flac?url";
import sounds6 from "./audio/characters/andy/andy-hurt-3.flac?url";
import sounds7 from "./audio/characters/andy/andy-hurt-4.flac?url";
import sounds8 from "./audio/characters/andy/andy-hurt-5.flac?url";
import sounds9 from "./audio/characters/andy/andy-hurt-6.flac?url";
import sounds10 from "./audio/characters/andy/andy-hurt-7.flac?url";
import sounds11 from "./audio/characters/andy/andy-hurt-8.flac?url";
import sounds12 from "./audio/characters/andy/andy-join-party-1.flac?url";
import sounds13 from "./audio/characters/andy/andy-join-party-2.flac?url";
import sounds14 from "./audio/characters/andy/andy-join-party-3.flac?url";
import sounds15 from "./audio/characters/andy/andy-look-here-1.flac?url";
import sounds16 from "./audio/characters/andy/andy-look-here-2.flac?url";
import sounds17 from "./audio/characters/andy/andy-misc-1.flac?url";
import sounds18 from "./audio/characters/andy/andy-misc-2.flac?url";
import sounds19 from "./audio/characters/andy/andy-misc-3.flac?url";
import sounds20 from "./audio/characters/andy/andy-near-death-1.flac?url";
import sounds21 from "./audio/characters/andy/andy-near-death-2.flac?url";
import sounds22 from "./audio/characters/andy/andy-near-death-3.flac?url";
import sounds23 from "./audio/characters/andy/andy-near-death-4.flac?url";
import sounds24 from "./audio/characters/andy/andy-new-level-1.flac?url";
import sounds25 from "./audio/characters/andy/andy-new-level-2.flac?url";
import sounds26 from "./audio/characters/andy/andy-pickup-1.flac?url";
import sounds27 from "./audio/characters/andy/andy-pickup-2.flac?url";
import sounds28 from "./audio/characters/andy/andy-pickup-3.flac?url";
import sounds29 from "./audio/characters/andy/andy-pickup-4.flac?url";
import sounds30 from "./audio/characters/andy/andy-pickup-5.flac?url";
import sounds31 from "./audio/characters/andy/andy-relief-1.flac?url";
import sounds32 from "./audio/characters/andy/andy-relief-2.flac?url";
import sounds33 from "./audio/characters/andy/andy-relief-3.flac?url";
import sounds34 from "./audio/characters/andy/andy-relief-4.flac?url";
import sounds35 from "./audio/characters/andy/andy-relief-5.flac?url";
import sounds36 from "./audio/characters/andy/andy-relief-6.flac?url";
import sounds37 from "./audio/characters/andy/andy-taunt-1.flac?url";
import sounds38 from "./audio/characters/andy/andy-taunt-2.flac?url";
import sounds39 from "./audio/characters/andy/andy-worried-1.flac?url";
import sounds40 from "./audio/characters/andy/andy-worried-2.flac?url";
import sounds41 from "./audio/characters/andy/andy-worried-3.flac?url";
import sounds42 from "./audio/characters/andy/andy-worried-4.flac?url";
import sounds43 from "./audio/characters/andy/andy-worried-5.flac?url";
import sounds44 from "./audio/characters/chad/chad-death-1.flac?url";
import sounds45 from "./audio/characters/chad/chad-hurt-1.flac?url";
import sounds46 from "./audio/characters/chad/chad-hurt-2.flac?url";
import sounds47 from "./audio/characters/chad/chad-hurt-3.flac?url";
import sounds48 from "./audio/characters/chad/chad-hurt-4.flac?url";
import sounds49 from "./audio/characters/chad/chad-hurt-5.flac?url";
import sounds50 from "./audio/characters/chad/chad-hurt-6.flac?url";
import sounds51 from "./audio/characters/chad/chad-hurt-7.flac?url";
import sounds52 from "./audio/characters/chad/chad-join-party-1.flac?url";
import sounds53 from "./audio/characters/chad/chad-level-complete-1.flac?url";
import sounds54 from "./audio/characters/chad/chad-level-complete-2.flac?url";
import sounds55 from "./audio/characters/chad/chad-level-complete-3.flac?url";
import sounds56 from "./audio/characters/chad/chad-look-here-1.flac?url";
import sounds57 from "./audio/characters/chad/chad-look-here-2.flac?url";
import sounds58 from "./audio/characters/chad/chad-look-here-3.flac?url";
import sounds59 from "./audio/characters/chad/chad-misc-1.flac?url";
import sounds60 from "./audio/characters/chad/chad-misc-2.flac?url";
import sounds61 from "./audio/characters/chad/chad-near-death-1.flac?url";
import sounds62 from "./audio/characters/chad/chad-near-death-2.flac?url";
import sounds63 from "./audio/characters/chad/chad-new-level-1.flac?url";
import sounds64 from "./audio/characters/chad/chad-new-level-2.flac?url";
import sounds65 from "./audio/characters/chad/chad-new-level-3.flac?url";
import sounds66 from "./audio/characters/chad/chad-new-level-4.flac?url";
import sounds67 from "./audio/characters/chad/chad-pickup-1.flac?url";
import sounds68 from "./audio/characters/chad/chad-pickup-2.flac?url";
import sounds69 from "./audio/characters/chad/chad-pickup-3.flac?url";
import sounds70 from "./audio/characters/chad/chad-taunt-1.flac?url";
import sounds71 from "./audio/characters/chad/chad-taunt-2.flac?url";
import sounds72 from "./audio/characters/chad/chad-taunt-3.flac?url";
import sounds73 from "./audio/characters/chad/chad-taunt-4.flac?url";
import sounds74 from "./audio/characters/chad/chad-taunt-5.flac?url";
import sounds75 from "./audio/characters/chad/chad-taunt-6.flac?url";
import sounds76 from "./audio/characters/chad/chad-worried-1.flac?url";
import sounds77 from "./audio/characters/chad/chad-worried-2.flac?url";
import sounds78 from "./audio/characters/chad/chad-worried-3.flac?url";
import sounds79 from "./audio/characters/cindy/cindy-death-1.flac?url";
import sounds80 from "./audio/characters/cindy/cindy-hurt-1.flac?url";
import sounds81 from "./audio/characters/cindy/cindy-hurt-2.flac?url";
import sounds82 from "./audio/characters/cindy/cindy-hurt-3.flac?url";
import sounds83 from "./audio/characters/cindy/cindy-join-party-1.flac?url";
import sounds84 from "./audio/characters/cindy/cindy-look-here-1.flac?url";
import sounds85 from "./audio/characters/cindy/cindy-look-here-2.flac?url";
import sounds86 from "./audio/characters/cindy/cindy-misc-1.flac?url";
import sounds87 from "./audio/characters/cindy/cindy-near-death-1.flac?url";
import sounds88 from "./audio/characters/cindy/cindy-new-level-1.flac?url";
import sounds89 from "./audio/characters/cindy/cindy-pickup-1.flac?url";
import sounds90 from "./audio/characters/cindy/cindy-relief-1.flac?url";
import sounds91 from "./audio/characters/cindy/cindy-taunt-1.flac?url";
import sounds92 from "./audio/characters/cindy/cindy-taunt-2.flac?url";
import sounds93 from "./audio/characters/cindy/cindy-worried-1.flac?url";
import sounds94 from "./audio/characters/clarice/clarice-death-1.flac?url";
import sounds95 from "./audio/characters/clarice/clarice-death-2.flac?url";
import sounds96 from "./audio/characters/clarice/clarice-hurt-1.flac?url";
import sounds97 from "./audio/characters/clarice/clarice-hurt-2.flac?url";
import sounds98 from "./audio/characters/clarice/clarice-hurt-3.flac?url";
import sounds99 from "./audio/characters/clarice/clarice-join-party-1.flac?url";
import sounds100 from "./audio/characters/clarice/clarice-look-here-1.flac?url";
import sounds101 from "./audio/characters/clarice/clarice-misc-1.flac?url";
import sounds102 from "./audio/characters/clarice/clarice-misc-2.flac?url";
import sounds103 from "./audio/characters/clarice/clarice-near-death.flac?url";
import sounds104 from "./audio/characters/clarice/clarice-new-level-1.flac?url";
import sounds105 from "./audio/characters/clarice/clarice-pickup-1.flac?url";
import sounds106 from "./audio/characters/clarice/clarice-relief-1.flac?url";
import sounds107 from "./audio/characters/clarice/clarice-relief-2.flac?url";
import sounds108 from "./audio/characters/clarice/clarice-taunt-1.flac?url";
import sounds109 from "./audio/characters/clarice/clarice-worried-1.flac?url";
import sounds110 from "./audio/characters/clyde/clyde-death-1.flac?url";
import sounds111 from "./audio/characters/clyde/clyde-hurt-1.flac?url";
import sounds112 from "./audio/characters/clyde/clyde-hurt-2.flac?url";
import sounds113 from "./audio/characters/clyde/clyde-join-party-1.flac?url";
import sounds114 from "./audio/characters/clyde/clyde-look-here-1.flac?url";
import sounds115 from "./audio/characters/clyde/clyde-look-here-2.flac?url";
import sounds116 from "./audio/characters/clyde/clyde-misc-1.flac?url";
import sounds117 from "./audio/characters/clyde/clyde-near-death.flac?url";
import sounds118 from "./audio/characters/clyde/clyde-new-level-1.flac?url";
import sounds119 from "./audio/characters/clyde/clyde-new-level-2.flac?url";
import sounds120 from "./audio/characters/clyde/clyde-new-level-3.flac?url";
import sounds121 from "./audio/characters/clyde/clyde-new-level-4.flac?url";
import sounds122 from "./audio/characters/clyde/clyde-pickup-1.flac?url";
import sounds123 from "./audio/characters/clyde/clyde-relief-1.flac?url";
import sounds124 from "./audio/characters/clyde/clyde-relief-2.flac?url";
import sounds125 from "./audio/characters/clyde/clyde-relief-3.flac?url";
import sounds126 from "./audio/characters/clyde/clyde-taunt-1.flac?url";
import sounds127 from "./audio/characters/clyde/clyde-taunt-2.flac?url";
import sounds128 from "./audio/characters/clyde/clyde-worried-1.flac?url";
import sounds129 from "./audio/characters/clyde/clyde-worried-2.flac?url";
import sounds130 from "./audio/characters/clyde/clyde-worried-3.flac?url";
import sounds131 from "./audio/characters/clyde/clyde-worried-4.flac?url";
import sounds132 from "./audio/characters/dusty-rusty/dusty-rusty-death-1.flac?url";
import sounds133 from "./audio/characters/dusty-rusty/dusty-rusty-death-2.flac?url";
import sounds134 from "./audio/characters/dusty-rusty/dusty-rusty-hurt-1.flac?url";
import sounds135 from "./audio/characters/dusty-rusty/dusty-rusty-hurt-10.flac?url";
import sounds136 from "./audio/characters/dusty-rusty/dusty-rusty-hurt-2.flac?url";
import sounds137 from "./audio/characters/dusty-rusty/dusty-rusty-hurt-3.flac?url";
import sounds138 from "./audio/characters/dusty-rusty/dusty-rusty-hurt-4.flac?url";
import sounds139 from "./audio/characters/dusty-rusty/dusty-rusty-hurt-5.flac?url";
import sounds140 from "./audio/characters/dusty-rusty/dusty-rusty-hurt-6.flac?url";
import sounds141 from "./audio/characters/dusty-rusty/dusty-rusty-hurt-7.flac?url";
import sounds142 from "./audio/characters/dusty-rusty/dusty-rusty-hurt-8.flac?url";
import sounds143 from "./audio/characters/dusty-rusty/dusty-rusty-hurt-9.flac?url";
import sounds144 from "./audio/characters/dusty-rusty/dusty-rusty-join-party-1.flac?url";
import sounds145 from "./audio/characters/dusty-rusty/dusty-rusty-join-party-2.flac?url";
import sounds146 from "./audio/characters/dusty-rusty/dusty-rusty-level-complete-1.flac?url";
import sounds147 from "./audio/characters/dusty-rusty/dusty-rusty-level-complete-2.flac?url";
import sounds148 from "./audio/characters/dusty-rusty/dusty-rusty-level-complete-3.flac?url";
import sounds149 from "./audio/characters/dusty-rusty/dusty-rusty-level-complete-4.flac?url";
import sounds150 from "./audio/characters/dusty-rusty/dusty-rusty-level-complete-5.flac?url";
import sounds151 from "./audio/characters/dusty-rusty/dusty-rusty-look-here-1.flac?url";
import sounds152 from "./audio/characters/dusty-rusty/dusty-rusty-look-here-2.flac?url";
import sounds153 from "./audio/characters/dusty-rusty/dusty-rusty-look-here-3.flac?url";
import sounds154 from "./audio/characters/dusty-rusty/dusty-rusty-look-here-4.flac?url";
import sounds155 from "./audio/characters/dusty-rusty/dusty-rusty-misc-1.flac?url";
import sounds156 from "./audio/characters/dusty-rusty/dusty-rusty-misc-2.flac?url";
import sounds157 from "./audio/characters/dusty-rusty/dusty-rusty-misc-3.flac?url";
import sounds158 from "./audio/characters/dusty-rusty/dusty-rusty-misc-4.flac?url";
import sounds159 from "./audio/characters/dusty-rusty/dusty-rusty-near-death-1.flac?url";
import sounds160 from "./audio/characters/dusty-rusty/dusty-rusty-near-death-2.flac?url";
import sounds161 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-1.flac?url";
import sounds162 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-10.flac?url";
import sounds163 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-11.flac?url";
import sounds164 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-12.flac?url";
import sounds165 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-2.flac?url";
import sounds166 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-3.flac?url";
import sounds167 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-4.flac?url";
import sounds168 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-5.flac?url";
import sounds169 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-6.flac?url";
import sounds170 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-7.flac?url";
import sounds171 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-8.flac?url";
import sounds172 from "./audio/characters/dusty-rusty/dusty-rusty-new-level-9.flac?url";
import sounds173 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-1.flac?url";
import sounds174 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-10-health.flac?url";
import sounds175 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-11-health.flac?url";
import sounds176 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-2.flac?url";
import sounds177 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-3.flac?url";
import sounds178 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-4.flac?url";
import sounds179 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-5.flac?url";
import sounds180 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-6.flac?url";
import sounds181 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-7.flac?url";
import sounds182 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-8.flac?url";
import sounds183 from "./audio/characters/dusty-rusty/dusty-rusty-pickup-9-health.flac?url";
import sounds184 from "./audio/characters/dusty-rusty/dusty-rusty-taunt-1.flac?url";
import sounds185 from "./audio/characters/dusty-rusty/dusty-rusty-taunt-2.flac?url";
import sounds186 from "./audio/characters/dusty-rusty/dusty-rusty-taunt-3.flac?url";
import sounds187 from "./audio/characters/dusty-rusty/dusty-rusty-taunt-4.flac?url";
import sounds188 from "./audio/characters/dusty-rusty/dusty-rusty-taunt-5.flac?url";
import sounds189 from "./audio/characters/dusty-rusty/dusty-rusty-taunt-6.flac?url";
import sounds190 from "./audio/characters/dusty-rusty/dusty-rusty-taunt-7.flac?url";
import sounds191 from "./audio/characters/dusty-rusty/dusty-rusty-taunt-8.flac?url";
import sounds192 from "./audio/characters/dusty-rusty/dusty-rusty-worried-1.flac?url";
import sounds193 from "./audio/characters/dusty-rusty/dusty-rusty-worried-2.flac?url";
import sounds194 from "./audio/characters/dusty-rusty/dusty-rusty-worried-3.flac?url";
import sounds195 from "./audio/characters/dusty-rusty/dusty-rusty-worried-4.flac?url";
import sounds196 from "./audio/characters/dusty-rusty/dusty-rusty-worried-5.flac?url";
import sounds197 from "./audio/characters/dusty-rusty/dusty-rusty-worried-6.flac?url";
import sounds198 from "./audio/characters/kyle/kyle-death-1.flac?url";
import sounds199 from "./audio/characters/kyle/kyle-death-2.flac?url";
import sounds200 from "./audio/characters/kyle/kyle-death-3.flac?url";
import sounds201 from "./audio/characters/kyle/kyle-hurt-1.flac?url";
import sounds202 from "./audio/characters/kyle/kyle-hurt-2.flac?url";
import sounds203 from "./audio/characters/kyle/kyle-hurt-4.flac?url";
import sounds204 from "./audio/characters/kyle/kyle-hurt-5.flac?url";
import sounds205 from "./audio/characters/kyle/kyle-hurt-6.flac?url";
import sounds206 from "./audio/characters/kyle/kyle-hurt-7.flac?url";
import sounds207 from "./audio/characters/kyle/kyle-hurt-8.flac?url";
import sounds208 from "./audio/characters/kyle/kyle-hurt-9.flac?url";
import sounds209 from "./audio/characters/kyle/kyle-join-party-1.flac?url";
import sounds210 from "./audio/characters/kyle/kyle-look-here-1.flac?url";
import sounds211 from "./audio/characters/kyle/kyle-look-here-2.flac?url";
import sounds212 from "./audio/characters/kyle/kyle-near-death-1.flac?url";
import sounds213 from "./audio/characters/kyle/kyle-near-death-2.flac?url";
import sounds214 from "./audio/characters/kyle/kyle-new-level-1.flac?url";
import sounds215 from "./audio/characters/kyle/kyle-pickup-1.flac?url";
import sounds216 from "./audio/characters/kyle/kyle-pickup-2.flac?url";
import sounds217 from "./audio/characters/kyle/kyle-relief-1.flac?url";
import sounds218 from "./audio/characters/kyle/kyle-taunt-1.flac?url";
import sounds219 from "./audio/characters/kyle/kyle-worried-1.flac?url";
import sounds220 from "./audio/characters/kyle/kyle-worried-2.flac?url";
import sounds221 from "./audio/characters/kyle/kyle-worried-3.flac?url";
import sounds222 from "./audio/characters/lucky-jack/lucky-jack-death-1.flac?url";
import sounds223 from "./audio/characters/lucky-jack/lucky-jack-death-2.flac?url";
import sounds224 from "./audio/characters/lucky-jack/lucky-jack-hurt-1.flac?url";
import sounds225 from "./audio/characters/lucky-jack/lucky-jack-hurt-2.flac?url";
import sounds226 from "./audio/characters/lucky-jack/lucky-jack-hurt-3.flac?url";
import sounds227 from "./audio/characters/lucky-jack/lucky-jack-hurt-4.flac?url";
import sounds228 from "./audio/characters/lucky-jack/lucky-jack-hurt-6.flac?url";
import sounds229 from "./audio/characters/lucky-jack/lucky-jack-join-party-1.flac?url";
import sounds230 from "./audio/characters/lucky-jack/lucky-jack-look-here.flac?url";
import sounds231 from "./audio/characters/lucky-jack/lucky-jack-misc-1.flac?url";
import sounds232 from "./audio/characters/lucky-jack/lucky-jack-near-death-1.flac?url";
import sounds233 from "./audio/characters/lucky-jack/lucky-jack-new-level-1.flac?url";
import sounds234 from "./audio/characters/lucky-jack/lucky-jack-new-level-2.flac?url";
import sounds235 from "./audio/characters/lucky-jack/lucky-jack-new-level-3.flac?url";
import sounds236 from "./audio/characters/lucky-jack/lucky-jack-pickup-1.flac?url";
import sounds237 from "./audio/characters/lucky-jack/lucky-jack-relief-1.flac?url";
import sounds238 from "./audio/characters/lucky-jack/lucky-jack-taunt-1.flac?url";
import sounds239 from "./audio/characters/lucky-jack/lucky-jack-taunt-2.flac?url";
import sounds240 from "./audio/characters/lucky-jack/lucky-jack-taunt-3.flac?url";
import sounds241 from "./audio/characters/lucky-jack/lucky-jack-taunt-4.flac?url";
import sounds242 from "./audio/characters/lucky-jack/lucky-jack-taunt-5.flac?url";
import sounds243 from "./audio/characters/lucky-jack/lucky-jack-worried-1.flac?url";
import sounds244 from "./audio/characters/nancy/nancy-death-3.flac?url";
import sounds245 from "./audio/characters/nancy/nancy-hurt-1.flac?url";
import sounds246 from "./audio/characters/nancy/nancy-hurt-2.flac?url";
import sounds247 from "./audio/characters/nancy/nancy-hurt-3.flac?url";
import sounds248 from "./audio/characters/nancy/nancy-hurt-4.flac?url";
import sounds249 from "./audio/characters/nancy/nancy-hurt-5.flac?url";
import sounds250 from "./audio/characters/nancy/nancy-hurt-6.flac?url";
import sounds251 from "./audio/characters/nancy/nancy-join-party-1.flac?url";
import sounds252 from "./audio/characters/nancy/nancy-join-party-2.flac?url";
import sounds253 from "./audio/characters/nancy/nancy-join-party-3.flac?url";
import sounds254 from "./audio/characters/nancy/nancy-look-here-1.flac?url";
import sounds255 from "./audio/characters/nancy/nancy-look-here-2.flac?url";
import sounds256 from "./audio/characters/nancy/nancy-look-here-3.flac?url";
import sounds257 from "./audio/characters/nancy/nancy-misc-1.flac?url";
import sounds258 from "./audio/characters/nancy/nancy-misc-2.flac?url";
import sounds259 from "./audio/characters/nancy/nancy-near-death-1.flac?url";
import sounds260 from "./audio/characters/nancy/nancy-near-death-2.flac?url";
import sounds261 from "./audio/characters/nancy/nancy-new-level-3.flac?url";
import sounds262 from "./audio/characters/nancy/nancy-pickup-1.flac?url";
import sounds263 from "./audio/characters/nancy/nancy-pickup-2.flac?url";
import sounds264 from "./audio/characters/nancy/nancy-relief-1.flac?url";
import sounds265 from "./audio/characters/nancy/nancy-relief-2.flac?url";
import sounds266 from "./audio/characters/nancy/nancy-relief-3.flac?url";
import sounds267 from "./audio/characters/nancy/nancy-taunt-1.flac?url";
import sounds268 from "./audio/characters/nancy/nancy-taunt-2.flac?url";
import sounds269 from "./audio/characters/nancy/nancy-worried-1.flac?url";
import sounds270 from "./audio/characters/nancy/nancy-worried-2.flac?url";
import sounds271 from "./audio/characters/nancy/nancy-worried-3.flac?url";
import sounds272 from "./audio/characters/santa/santa-death-1.flac?url";
import sounds273 from "./audio/characters/santa/santa-ho-ho-ho-1.flac?url";
import sounds274 from "./audio/characters/santa/santa-ho-ho-ho-2.flac?url";
import sounds275 from "./audio/characters/santa/santa-ho-ho-ho-3.flac?url";
import sounds276 from "./audio/characters/santa/santa-hurt-1.flac?url";
import sounds277 from "./audio/characters/santa/santa-hurt-2.flac?url";
import sounds278 from "./audio/characters/santa/santa-hurt-3.flac?url";
import sounds279 from "./audio/characters/santa/santa-hurt-4.flac?url";
import sounds280 from "./audio/characters/santa/santa-hurt-5.flac?url";
import sounds281 from "./audio/characters/santa/santa-hurt-6.flac?url";
import sounds282 from "./audio/characters/santa/santa-hurt-7.flac?url";
import sounds283 from "./audio/characters/santa/santa-hurt-8.flac?url";
import sounds284 from "./audio/characters/santa/santa-join-1.flac?url";
import sounds285 from "./audio/characters/santa/santa-new-level-1.flac?url";
import sounds286 from "./audio/characters/santa/santa-new-level-2.flac?url";
import sounds287 from "./audio/characters/santa/santa-pickup-2.flac?url";
import sounds288 from "./audio/characters/santa/santa-pickup-gun-1.flac?url";
import sounds289 from "./audio/characters/santa/santa-taunt-1.flac?url";
import sounds290 from "./audio/characters/santa/santa-taunt-2.flac?url";
import sounds291 from "./audio/characters/santa/santa-taunt-3.flac?url";
import sounds292 from "./audio/characters/santa/santa-taunt-4.flac?url";
import sounds293 from "./audio/characters/santa/santa-taunt-5.flac?url";
import sounds294 from "./audio/characters/santa/santa-taunt-6.flac?url";
import sounds295 from "./audio/characters/santa/santa-taunt-7.flac?url";
import sounds296 from "./audio/characters/santa/santa-worried-1.flac?url";
import sounds297 from "./audio/characters/santa/santa-worried-2.flac?url";
import sounds298 from "./audio/characters/simon/simon-death-1.flac?url";
import sounds299 from "./audio/characters/simon/simon-hurt-1.flac?url";
import sounds300 from "./audio/characters/simon/simon-hurt-2.flac?url";
import sounds301 from "./audio/characters/simon/simon-hurt-3.flac?url";
import sounds302 from "./audio/characters/simon/simon-hurt-4.flac?url";
import sounds303 from "./audio/characters/simon/simon-hurt-5.flac?url";
import sounds304 from "./audio/characters/simon/simon-hurt-6.flac?url";
import sounds305 from "./audio/characters/simon/simon-hurt-7.flac?url";
import sounds306 from "./audio/characters/simon/simon-join-party-1.flac?url";
import sounds307 from "./audio/characters/simon/simon-look-here-1.flac?url";
import sounds308 from "./audio/characters/simon/simon-look-here-2.flac?url";
import sounds309 from "./audio/characters/simon/simon-near-death-2.flac?url";
import sounds310 from "./audio/characters/simon/simon-pickup-item-1.flac?url";
import sounds311 from "./audio/characters/simon/simon-pickup-item-2.flac?url";
import sounds312 from "./audio/characters/simon/simon-pickup-item-3.flac?url";
import sounds313 from "./audio/characters/simon/simon-relief-1.flac?url";
import sounds314 from "./audio/characters/simon/simon-taunt-1.flac?url";
import sounds315 from "./audio/characters/simon/simon-taunt-2.flac?url";
import sounds316 from "./audio/characters/simon/simon-worried-1.flac?url";
import sounds317 from "./audio/characters/simon/simon-worried-2.flac?url";
import sounds318 from "./audio/characters/simon/simon-worried-3.flac?url";
import sounds319 from "./audio/characters/takeshi/takeshi-death-1.flac?url";
import sounds320 from "./audio/characters/takeshi/takeshi-hurt-1.flac?url";
import sounds321 from "./audio/characters/takeshi/takeshi-hurt-2.flac?url";
import sounds322 from "./audio/characters/takeshi/takeshi-hurt-3.flac?url";
import sounds323 from "./audio/characters/takeshi/takeshi-hurt-4.flac?url";
import sounds324 from "./audio/characters/takeshi/takeshi-hurt-6.flac?url";
import sounds325 from "./audio/characters/takeshi/takeshi-hurt-7.flac?url";
import sounds326 from "./audio/characters/takeshi/takeshi-hurt-8.flac?url";
import sounds327 from "./audio/characters/takeshi/takeshi-join-party-1.flac?url";
import sounds328 from "./audio/characters/takeshi/takeshi-join-party-2.flac?url";
import sounds329 from "./audio/characters/takeshi/takeshi-level-complete-1.flac?url";
import sounds330 from "./audio/characters/takeshi/takeshi-level-complete-2.flac?url";
import sounds331 from "./audio/characters/takeshi/takeshi-look-here-1.flac?url";
import sounds332 from "./audio/characters/takeshi/takeshi-misc-1.flac?url";
import sounds333 from "./audio/characters/takeshi/takeshi-near-death-1.flac?url";
import sounds334 from "./audio/characters/takeshi/takeshi-new-level-1.flac?url";
import sounds335 from "./audio/characters/takeshi/takeshi-pickup-1.flac?url";
import sounds336 from "./audio/characters/takeshi/takeshi-pickup-2.flac?url";
import sounds337 from "./audio/characters/takeshi/takeshi-taunt-1.flac?url";
import sounds338 from "./audio/characters/takeshi/takeshi-taunt-2.flac?url";
import sounds339 from "./audio/characters/takeshi/takeshi-taunt-3.flac?url";
import sounds340 from "./audio/characters/takeshi/takeshi-taunt-4.flac?url";
import sounds341 from "./audio/characters/takeshi/takeshi-worried-1.flac?url";
import sounds342 from "./audio/characters/takeshi/takeshi-worried-2.flac?url";
import sounds343 from "./audio/characters/takeshi/takeshi-worried-3.flac?url";
import sounds344 from "./audio/characters/wendy/wendy-death-1.flac?url";
import sounds345 from "./audio/characters/wendy/wendy-death-2.flac?url";
import sounds346 from "./audio/characters/wendy/wendy-death-3.flac?url";
import sounds347 from "./audio/characters/wendy/wendy-death-4.flac?url";
import sounds348 from "./audio/characters/wendy/wendy-hurt-1.flac?url";
import sounds349 from "./audio/characters/wendy/wendy-hurt-2.flac?url";
import sounds350 from "./audio/characters/wendy/wendy-hurt-3.flac?url";
import sounds351 from "./audio/characters/wendy/wendy-hurt-4.flac?url";
import sounds352 from "./audio/characters/wendy/wendy-hurt-6.flac?url";
import sounds353 from "./audio/characters/wendy/wendy-hurt-7.flac?url";
import sounds354 from "./audio/characters/wendy/wendy-join-party-1.flac?url";
import sounds355 from "./audio/characters/wendy/wendy-join-party-2.flac?url";
import sounds356 from "./audio/characters/wendy/wendy-join-party-3.flac?url";
import sounds357 from "./audio/characters/wendy/wendy-join-party-4.flac?url";
import sounds358 from "./audio/characters/wendy/wendy-look-here-1.flac?url";
import sounds359 from "./audio/characters/wendy/wendy-look-here-2.flac?url";
import sounds360 from "./audio/characters/wendy/wendy-look-here-3.flac?url";
import sounds361 from "./audio/characters/wendy/wendy-misc-2.flac?url";
import sounds362 from "./audio/characters/wendy/wendy-misc-3.flac?url";
import sounds363 from "./audio/characters/wendy/wendy-near-death-1.flac?url";
import sounds364 from "./audio/characters/wendy/wendy-near-death-2.flac?url";
import sounds365 from "./audio/characters/wendy/wendy-near-death-4.flac?url";
import sounds366 from "./audio/characters/wendy/wendy-near-death-5.flac?url";
import sounds367 from "./audio/characters/wendy/wendy-new-level-1.flac?url";
import sounds368 from "./audio/characters/wendy/wendy-new-level-2.flac?url";
import sounds369 from "./audio/characters/wendy/wendy-new-level-3.flac?url";
import sounds370 from "./audio/characters/wendy/wendy-new-level-4.flac?url";
import sounds371 from "./audio/characters/wendy/wendy-pickup-1.flac?url";
import sounds372 from "./audio/characters/wendy/wendy-pickup-2.flac?url";
import sounds373 from "./audio/characters/wendy/wendy-pickup-3.flac?url";
import sounds374 from "./audio/characters/wendy/wendy-pickup-4.flac?url";
import sounds375 from "./audio/characters/wendy/wendy-pickup-5.flac?url";
import sounds376 from "./audio/characters/wendy/wendy-pickup-6.flac?url";
import sounds377 from "./audio/characters/wendy/wendy-pickup-7.flac?url";
import sounds378 from "./audio/characters/wendy/wendy-relief-1.flac?url";
import sounds379 from "./audio/characters/wendy/wendy-relief-2.flac?url";
import sounds380 from "./audio/characters/wendy/wendy-relief-3.flac?url";
import sounds381 from "./audio/characters/wendy/wendy-relief-4.flac?url";
import sounds382 from "./audio/characters/wendy/wendy-relief-5.flac?url";
import sounds383 from "./audio/characters/wendy/wendy-relief-6.flac?url";
import sounds384 from "./audio/characters/wendy/wendy-taunt-1.flac?url";
import sounds385 from "./audio/characters/wendy/wendy-taunt-2.flac?url";
import sounds386 from "./audio/characters/wendy/wendy-taunt-4.flac?url";
import sounds387 from "./audio/characters/wendy/wendy-taunt-5.flac?url";
import sounds388 from "./audio/characters/wendy/wendy-taunt3.flac?url";
import sounds389 from "./audio/characters/wendy/wendy-worried-1.flac?url";
import sounds390 from "./audio/characters/wendy/wendy-worried-2.flac?url";
import sounds391 from "./audio/characters/wendy/wendy-worried-3.flac?url";
import sounds392 from "./audio/characters/wendy/wendy-worried-4.flac?url";
import sounds393 from "./audio/environment/chain-link-fence-1.flac?url";
import sounds394 from "./audio/environment/chain-link-fence-2.flac?url";
import sounds395 from "./audio/environment/chain-link-fence-3.flac?url";
import sounds396 from "./audio/environment/elevator-ding.flac?url";
import sounds397 from "./audio/environment/elevator-door-close.flac?url";
import sounds398 from "./audio/environment/elevator-door-open.flac?url";
import sounds399 from "./audio/environment/heavy-switch-throw.flac?url";
import sounds400 from "./audio/environment/light-power-on-1.wav?url";
import sounds401 from "./audio/environment/power-warm-up-1.flac?url";
import sounds402 from "./audio/food/individual/cabbage-hit-1.flac?url";
import sounds403 from "./audio/food/individual/cabbage-hit-10.flac?url";
import sounds404 from "./audio/food/individual/cabbage-hit-11.flac?url";
import sounds405 from "./audio/food/individual/cabbage-hit-2.flac?url";
import sounds406 from "./audio/food/individual/cabbage-hit-3.flac?url";
import sounds407 from "./audio/food/individual/cabbage-hit-4.flac?url";
import sounds408 from "./audio/food/individual/cabbage-hit-5.flac?url";
import sounds409 from "./audio/food/individual/cabbage-hit-6.flac?url";
import sounds410 from "./audio/food/individual/cabbage-hit-7.flac?url";
import sounds411 from "./audio/food/individual/cabbage-hit-8.flac?url";
import sounds412 from "./audio/food/individual/melon-plop-1.flac?url";
import sounds413 from "./audio/food/individual/melon-plop-2.flac?url";
import sounds414 from "./audio/food/individual/melon-plop-3.flac?url";
import sounds415 from "./audio/food/individual/melon-plop-4.flac?url";
import sounds416 from "./audio/food/individual/melon-plop-5.flac?url";
import sounds417 from "./audio/food/individual/melon-plop-6.flac?url";
import sounds418 from "./audio/guns/casing-drops/casing-drop-board-1.flac?url";
import sounds419 from "./audio/guns/casing-drops/casing-drop-board-2.flac?url";
import sounds420 from "./audio/guns/casing-drops/casing-drop-board-3.flac?url";
import sounds421 from "./audio/guns/casing-drops/casing-drop-board-4.flac?url";
import sounds422 from "./audio/guns/casing-drops/shotgun-casing-drop-1.mp3?url";
import sounds423 from "./audio/guns/misc/dry-fire-1.mp3?url";
import sounds424 from "./audio/guns/misc/dry-fire-2.mp3?url";
import sounds425 from "./audio/guns/misc/dry-fire-3.mp3?url";
import sounds426 from "./audio/guns/misc/magazine-load-1.mp3?url";
import sounds427 from "./audio/guns/pistol/M1911-pickup.flac?url";
import sounds428 from "./audio/guns/pistol/deagle-shot-1.mp3?url";
import sounds429 from "./audio/guns/pistol/deagle-shot-2.mp3?url";
import sounds430 from "./audio/guns/pistol/m1911-dry-fire.flac?url";
import sounds431 from "./audio/guns/pistol/m1911-reload-1.flac?url";
import sounds432 from "./audio/guns/pistol/pistol-cock-1.mp3?url";
import sounds433 from "./audio/guns/pistol/pistol-shot-1.mp3?url";
import sounds434 from "./audio/guns/pistol/pistol-shot-2.mp3?url";
import sounds435 from "./audio/guns/pistol/pistol2-shot-1.mp3?url";
import sounds436 from "./audio/guns/revolver/revolver-dry-fire.flac?url";
import sounds437 from "./audio/guns/revolver/revolver-insert-shell-1.flac?url";
import sounds438 from "./audio/guns/revolver/revolver-insert-shell-2.flac?url";
import sounds439 from "./audio/guns/revolver/revolver-insert-shell-3.flac?url";
import sounds440 from "./audio/guns/revolver/revolver-pickup.flac?url";
import sounds441 from "./audio/guns/revolver/revolver-reload-finish.flac?url";
import sounds442 from "./audio/guns/revolver/revolver-reload-start.flac?url";
import sounds443 from "./audio/guns/revolver/revolver-shot-3.mp3?url";
import sounds444 from "./audio/guns/rifle/ar-15-reload-1.flac?url";
import sounds445 from "./audio/guns/rifle/ar-15-reload-empty.flac?url";
import sounds446 from "./audio/guns/rifle/rifle-shot-1.mp3?url";
import sounds447 from "./audio/guns/rifle/rifle-shot-2.mp3?url";
import sounds448 from "./audio/guns/rifle/rifle-shot-3.mp3?url";
import sounds449 from "./audio/guns/rifle/rifle2-shot-1.mp3?url";
import sounds450 from "./audio/guns/shotgun/shotgun-load-shell-2.flac?url";
import sounds451 from "./audio/guns/shotgun/shotgun-pump-1.mp3?url";
import sounds452 from "./audio/guns/shotgun/shotgun-shot-1.mp3?url";
import sounds453 from "./audio/guns/shotgun/shotgun-shot-2.mp3?url";
import sounds454 from "./audio/guns/shotgun/shotgun-shot-3.mp3?url";
import sounds455 from "./audio/impacts/flesh-hit-1.flac?url";
import sounds456 from "./audio/impacts/flesh-hit-2.flac?url";
import sounds457 from "./audio/impacts/flesh-hit-3.flac?url";
import sounds458 from "./audio/impacts/flesh-hit-4.flac?url";
import sounds459 from "./audio/impacts/flesh-hit-bat-1.flac?url";
import sounds460 from "./audio/impacts/flesh-hit-bat-2.flac?url";
import sounds461 from "./audio/impacts/piano-hit-1.flac?url";
import sounds462 from "./audio/impacts/piano-hit-2.flac?url";
import sounds463 from "./audio/impacts/vending-machine-hit-1.flac?url";
import sounds464 from "./audio/impacts/vending-machine-hit-2.flac?url";
import sounds465 from "./audio/impacts/wall-hit-1.flac?url";
import sounds466 from "./audio/impacts/wall-hit-2.flac?url";
import sounds467 from "./audio/impacts/wall-hit-3.flac?url";
import sounds468 from "./audio/impacts/wall-hit-4.flac?url";
import sounds469 from "./audio/impacts/zombie-bite-1.flac?url";
import sounds470 from "./audio/impacts/zombie-bite-2.flac?url";
import sounds471 from "./audio/misc/glow-stick-drop-1.flac?url";
import sounds472 from "./audio/misc/glow-stick-drop-2.flac?url";
import sounds473 from "./audio/misc/pop1.flac?url";
import sounds474 from "./audio/misc/quarter-drop-1.flac?url";
import sounds475 from "./audio/moms-kitchen/machine-loop-1.flac?url";
import sounds476 from "./audio/music/bass-groove-loop-1.flac?url";
import sounds477 from "./audio/weapons/baseball-bat-pickup-1.flac?url";
import sounds478 from "./audio/weapons/baseball-bat-pickup-2.flac?url";
import sounds479 from "./audio/weapons/sword-shing-1.flac?url";
import sounds480 from "./audio/weapons/sword-shing-2.flac?url";
import sounds481 from "./audio/weapons/sword-shing-3.flac?url";
import sounds482 from "./audio/weapons/sword-swoosh-1.flac?url";
import sounds483 from "./audio/weapons/sword-swoosh-2.flac?url";
import sounds484 from "./audio/weapons/sword-swoosh-3.flac?url";
import sounds485 from "./audio/zombie/kevin-zombie-1.flac?url";
import sounds486 from "./audio/zombie/kevin-zombie-10.flac?url";
import sounds487 from "./audio/zombie/kevin-zombie-11.flac?url";
import sounds488 from "./audio/zombie/kevin-zombie-12.flac?url";
import sounds489 from "./audio/zombie/kevin-zombie-13.flac?url";
import sounds490 from "./audio/zombie/kevin-zombie-14.flac?url";
import sounds491 from "./audio/zombie/kevin-zombie-15.flac?url";
import sounds492 from "./audio/zombie/kevin-zombie-17.flac?url";
import sounds493 from "./audio/zombie/kevin-zombie-18.flac?url";
import sounds494 from "./audio/zombie/kevin-zombie-19.flac?url";
import sounds495 from "./audio/zombie/kevin-zombie-2.flac?url";
import sounds496 from "./audio/zombie/kevin-zombie-20.flac?url";
import sounds497 from "./audio/zombie/kevin-zombie-21.flac?url";
import sounds498 from "./audio/zombie/kevin-zombie-23.flac?url";
import sounds499 from "./audio/zombie/kevin-zombie-24.flac?url";
import sounds500 from "./audio/zombie/kevin-zombie-25.flac?url";
import sounds501 from "./audio/zombie/kevin-zombie-26.flac?url";
import sounds502 from "./audio/zombie/kevin-zombie-27.flac?url";
import sounds503 from "./audio/zombie/kevin-zombie-28.flac?url";
import sounds504 from "./audio/zombie/kevin-zombie-29.flac?url";
import sounds505 from "./audio/zombie/kevin-zombie-3.flac?url";
import sounds506 from "./audio/zombie/kevin-zombie-30.flac?url";
import sounds507 from "./audio/zombie/kevin-zombie-31.flac?url";
import sounds508 from "./audio/zombie/kevin-zombie-32.flac?url";
import sounds509 from "./audio/zombie/kevin-zombie-33.flac?url";
import sounds510 from "./audio/zombie/kevin-zombie-34.flac?url";
import sounds511 from "./audio/zombie/kevin-zombie-35.flac?url";
import sounds512 from "./audio/zombie/kevin-zombie-36.flac?url";
import sounds513 from "./audio/zombie/kevin-zombie-37.flac?url";
import sounds514 from "./audio/zombie/kevin-zombie-38.flac?url";
import sounds515 from "./audio/zombie/kevin-zombie-39.flac?url";
import sounds516 from "./audio/zombie/kevin-zombie-4.flac?url";
import sounds517 from "./audio/zombie/kevin-zombie-5.flac?url";
import sounds518 from "./audio/zombie/kevin-zombie-7.flac?url";
import sounds519 from "./audio/zombie/kevin-zombie-8.flac?url";
import sounds520 from "./audio/zombie/kevin-zombie-9.flac?url";
import sounds521 from "./audio/zombie/perry-zombie-1.flac?url";
import sounds522 from "./audio/zombie/perry-zombie-10.flac?url";
import sounds523 from "./audio/zombie/perry-zombie-2.flac?url";
import sounds524 from "./audio/zombie/perry-zombie-3.flac?url";
import sounds525 from "./audio/zombie/perry-zombie-4.flac?url";
import sounds526 from "./audio/zombie/perry-zombie-6.flac?url";
import sounds527 from "./audio/zombie/perry-zombie-7.flac?url";
import sounds528 from "./audio/zombie/perry-zombie-8.flac?url";
import sounds529 from "./audio/zombie/perry-zombie-9.flac?url";
import sounds530 from "./audio/zombie/rachel-zombie-1.flac?url";
import sounds531 from "./audio/zombie/rachel-zombie-10.flac?url";
import sounds532 from "./audio/zombie/rachel-zombie-11.flac?url";
import sounds533 from "./audio/zombie/rachel-zombie-12.flac?url";
import sounds534 from "./audio/zombie/rachel-zombie-13.flac?url";
import sounds535 from "./audio/zombie/rachel-zombie-2.flac?url";
import sounds536 from "./audio/zombie/rachel-zombie-3.flac?url";
import sounds537 from "./audio/zombie/rachel-zombie-4.flac?url";
import sounds538 from "./audio/zombie/rachel-zombie-5.flac?url";
import sounds539 from "./audio/zombie/rachel-zombie-6.flac?url";
import sounds540 from "./audio/zombie/rachel-zombie-7.flac?url";
import sounds541 from "./audio/zombie/rachel-zombie-8.flac?url";
import sounds542 from "./audio/zombie/rachel-zombie-9.flac?url";
import sounds543 from "./audio/zombie/spitter-spit-1.flac?url";
import sounds544 from "./audio/zombie/spitter-spit-2.flac?url";
import sounds545 from "./audio/zombie/spitter-spit-3.flac?url";
import fonts0 from "./fonts/Oswald/oswald.ttf?url";
import fonts1 from "./fonts/capture_it/capture_it.ttf?url";
const images = {
  "andyHead": images0,
  "andyLeftArm": images1,
  "andyLeftHand": images2,
  "andyRightArm": images3,
  "andyRightHand": images4,
  "andyTorso": images5,
  "chadHead": images6,
  "chadLeftArm": images7,
  "chadLeftHand": images8,
  "chadRightArm": images9,
  "chadRightHand": images10,
  "chadTorso": images11,
  "cindyHead": images12,
  "cindyLeftArm": images13,
  "cindyLeftHand": images14,
  "cindyRightArm": images15,
  "cindyRightHand": images16,
  "cindyTorso": images17,
  "clariceHead": images18,
  "clariceLeftArm": images19,
  "clariceLeftHand": images20,
  "clariceRightArm": images21,
  "clariceRightHand": images22,
  "clariceTorso": images23,
  "dustyRustyHead": images24,
  "dustyRustyLeftArm": images25,
  "dustyRustyLeftHand": images26,
  "dustyRustyRightArm": images27,
  "dustyRustyRightHand": images28,
  "dustyRustyTorso": images29,
  "kyleHead": images30,
  "kyleLeftArm": images31,
  "kyleLeftHand": images32,
  "kyleRightArm": images33,
  "kyleRightHand": images34,
  "kyleTorso": images35,
  "luckyJackHead": images36,
  "luckyJackLeftArm": images37,
  "luckyJackLeftHand": images38,
  "luckyJackRightArm": images39,
  "luckyJackRightHand": images40,
  "luckyJackTorso": images41,
  "mikeHead": images42,
  "mikeLeftArm": images43,
  "mikeLeftHand": images44,
  "mikeRightArm": images45,
  "mikeRightHand": images46,
  "mikeTorso": images47,
  "nancyHead": images48,
  "nancyLeftArm": images49,
  "nancyLeftHand": images50,
  "nancyRightArm": images51,
  "nancyRightHand": images52,
  "nancyTorso": images53,
  "santaHead": images54,
  "santaLeftArm": images55,
  "santaLeftHand": images56,
  "santaRightArm": images57,
  "santaRightHand": images58,
  "santaTorso": images59,
  "simonHead": images60,
  "simonLeftArm": images61,
  "simonLeftHand": images62,
  "simonRightArm": images63,
  "simonRightHand": images64,
  "simonTorso": images65,
  "takeshiHead": images66,
  "takeshiLeftArm": images67,
  "takeshiLeftHand": images68,
  "takeshiRightArm": images69,
  "takeshiRightHand": images70,
  "takeshiTorso": images71,
  "wendyHead": images72,
  "wendyLeftArm": images73,
  "wendyLeftHand": images74,
  "wendyRightArm": images75,
  "wendyRightHand": images76,
  "wendyTorso": images77,
  "glowStick1": images78,
  "glowStick2": images79,
  "glowStick3": images80,
  "healthOverlay": images81,
  "impactParticle": images82,
  "bathroom": images83,
  "sink1": images84,
  "sink3": images85,
  "sinkGroup1": images86,
  "sinkGroup2": images87,
  "sinkGroup3": images88,
  "sinkGroup4": images89,
  "sinkGroup5": images90,
  "sinkGroup6": images91,
  "sink2": images92,
  "toilet1": images93,
  "toilet2": images94,
  "toilet3": images95,
  "toilet4": images96,
  "toilet5": images97,
  "bookcase1": images98,
  "bookcase2": images99,
  "boxPile1": images100,
  "boxPile2": images101,
  "boxShelf1": images102,
  "boxShelf2": images103,
  "chainLinkFence": images104,
  "door1": images105,
  "door2": images106,
  "fancyFurniture": images107,
  "fancyRug1": images108,
  "fence": images109,
  "industrialCarpet001": images110,
  "industrialCarpet002": images111,
  "bathroomTileFloor1": images112,
  "bathroomTileFloor2": images113,
  "bathroomTileFloor3": images114,
  "bathroomTileFloor4": images115,
  "carpet": images116,
  "cement": images117,
  "granite1": images118,
  "granite2": images119,
  "granite3": images120,
  "marble1": images121,
  "oldPlankFlooring1": images122,
  "oldPlankFlooring2": images123,
  "steelFloor": images124,
  "tileFloor1": images125,
  "tileFloor10": images126,
  "tileFloor11": images127,
  "tileFloor12": images128,
  "tileFloor13": images129,
  "tileFloor14": images130,
  "tileFloor15": images131,
  "tileFloor2": images132,
  "tileFloor3": images133,
  "tileFloor4": images134,
  "tileFloor5": images135,
  "tileFloor6": images136,
  "tileFloor7": images137,
  "tileFloor8": images138,
  "tileFloor9": images139,
  "woodFloor1": images140,
  "woodFloor2": images141,
  "woodFloor3": images142,
  "woodenFloor": images143,
  "furniture": images144,
  "fancyChair1": images145,
  "fancyEndTable1": images146,
  "fancyEndTable2": images147,
  "fancyTable1": images148,
  "fancyTable2": images149,
  "lobbyDesk1": images150,
  "piano": images151,
  "transformer": images152,
  "shelf1": images153,
  "shopCounter1": images154,
  "shopCounter2": images155,
  "shopCounter3": images156,
  "stairs": images157,
  "vendingMachine1": images158,
  "vendingMachine2": images159,
  "vendingMachine3": images160,
  "vendingMachineGlow1": images161,
  "vendingMachineGlow2": images162,
  "vendingMachineGlow3": images163,
  "wall1": images164,
  "waterCooler": images165,
  "favicon": images166,
  "healthKit": images167,
  "pointLight": images168,
  "muzzleFlash1": images169,
  "muzzleFlash10": images170,
  "muzzleFlash11": images171,
  "muzzleFlash12": images172,
  "muzzleFlash13": images173,
  "muzzleFlash14": images174,
  "muzzleFlash15": images175,
  "muzzleFlash16": images176,
  "muzzleFlash2": images177,
  "muzzleFlash3": images178,
  "muzzleFlash4": images179,
  "muzzleFlash5": images180,
  "muzzleFlash6": images181,
  "muzzleFlash7": images182,
  "muzzleFlash8": images183,
  "muzzleFlash9": images184,
  "pistolCasing": images185,
  "rifleCasing": images186,
  "shotgunCasing": images187,
  "solidCircle": images188,
  "blob1": images189,
  "blob2": images190,
  "blob3": images191,
  "blob4": images192,
  "blob5": images193,
  "blobGlow1": images194,
  "blobGlow2": images195,
  "blobGlow3": images196,
  "blobGlow4": images197,
  "blobGlow5": images198,
  "splatGlow1": images199,
  "splatGlow2": images200,
  "splatGlow3": images201,
  "splatGlow4": images202,
  "splatGlow5": images203,
  "splatGlow6": images204,
  "splatGlow7": images205,
  "splat1": images206,
  "splat2": images207,
  "splat3": images208,
  "splat4": images209,
  "splat5": images210,
  "splat6": images211,
  "splat7": images212,
  "ak47Hold": images213,
  "ak47Pickup": images214,
  "ar15Pickup": images215,
  "ar15Hold": images216,
  "axe": images217,
  "baseballBatHold": images218,
  "baseballBatPickup": images219,
  "desertEagleHold": images220,
  "desertEaglePickup": images221,
  "doubleBarrelShotgunHold": images222,
  "doubleBarrelShotgunPickup": images223,
  "fiveSevenHold": images224,
  "fiveSevenPickup": images225,
  "glockHold": images226,
  "glockPickup": images227,
  "katana": images228,
  "akMagazine": images229,
  "p90Magazine": images230,
  "pistolMagazine": images231,
  "revolverRound": images232,
  "rifleMagazine": images233,
  "shotgunShellPair": images234,
  "shotgunShell": images235,
  "magnumHold": images236,
  "magnumPickup": images237,
  "p90Hold": images238,
  "p90Pickup": images239,
  "remington870Hold": images240,
  "remingtonPickup": images241,
  "spas12Hold": images242,
  "spas12Pickup": images243,
  "crawler1": images244,
  "crawler2": images245,
  "crawler3": images246,
  "crawlerHead1": images247,
  "crawlerHead2": images248,
  "crawlerHead3": images249,
  "crawlerLeftArm1": images250,
  "crawlerLeftArm2": images251,
  "crawlerLeftArm3": images252,
  "crawlerLeftHand1": images253,
  "crawlerLeftHand2": images254,
  "crawlerLeftHand3": images255,
  "crawlerRightArm1": images256,
  "crawlerRightArm2": images257,
  "crawlerRightArm3": images258,
  "crawlerRightHand1": images259,
  "crawlerRightHand2": images260,
  "crawlerRightHand3": images261,
  "crawlerTorso1": images262,
  "crawlerTorso2": images263,
  "crawlerTorso3": images264,
  "crawler": images265,
  "heavy": images266,
  "necromancer": images267,
  "spitter": images268,
  "zombie1": images269,
  "zombie2": images270,
  "zombie3": images271,
  "zombieHead1": images272,
  "zombieHead2": images273,
  "zombieHead3": images274,
  "zombieLeftArm1": images275,
  "zombieLeftArm2": images276,
  "zombieLeftArm3": images277,
  "zombieLeftHand1": images278,
  "zombieLeftHand2": images279,
  "zombieLeftHand3": images280,
  "zombieLegs1": images281,
  "zombieLegs2": images282,
  "zombieLegs3": images283,
  "zombieRightArm1": images284,
  "zombieRightArm2": images285,
  "zombieRightArm3": images286,
  "zombieRightHand1": images287,
  "zombieRightHand2": images288,
  "zombieRightHand3": images289,
  "zombieTorso1": images290,
  "zombieTorso2": images291,
  "zombieTorso3": images292,
};
export type ImageName = keyof typeof images;
const sounds = {
  "andyDeath1": sounds0,
  "andyDeath2": sounds1,
  "andyDeath3": sounds2,
  "andyDeath4": sounds3,
  "andyHurt1": sounds4,
  "andyHurt2": sounds5,
  "andyHurt3": sounds6,
  "andyHurt4": sounds7,
  "andyHurt5": sounds8,
  "andyHurt6": sounds9,
  "andyHurt7": sounds10,
  "andyHurt8": sounds11,
  "andyJoinParty1": sounds12,
  "andyJoinParty2": sounds13,
  "andyJoinParty3": sounds14,
  "andyLookHere1": sounds15,
  "andyLookHere2": sounds16,
  "andyMisc1": sounds17,
  "andyMisc2": sounds18,
  "andyMisc3": sounds19,
  "andyNearDeath1": sounds20,
  "andyNearDeath2": sounds21,
  "andyNearDeath3": sounds22,
  "andyNearDeath4": sounds23,
  "andyNewLevel1": sounds24,
  "andyNewLevel2": sounds25,
  "andyPickup1": sounds26,
  "andyPickup2": sounds27,
  "andyPickup3": sounds28,
  "andyPickup4": sounds29,
  "andyPickup5": sounds30,
  "andyRelief1": sounds31,
  "andyRelief2": sounds32,
  "andyRelief3": sounds33,
  "andyRelief4": sounds34,
  "andyRelief5": sounds35,
  "andyRelief6": sounds36,
  "andyTaunt1": sounds37,
  "andyTaunt2": sounds38,
  "andyWorried1": sounds39,
  "andyWorried2": sounds40,
  "andyWorried3": sounds41,
  "andyWorried4": sounds42,
  "andyWorried5": sounds43,
  "chadDeath1": sounds44,
  "chadHurt1": sounds45,
  "chadHurt2": sounds46,
  "chadHurt3": sounds47,
  "chadHurt4": sounds48,
  "chadHurt5": sounds49,
  "chadHurt6": sounds50,
  "chadHurt7": sounds51,
  "chadJoinParty1": sounds52,
  "chadLevelComplete1": sounds53,
  "chadLevelComplete2": sounds54,
  "chadLevelComplete3": sounds55,
  "chadLookHere1": sounds56,
  "chadLookHere2": sounds57,
  "chadLookHere3": sounds58,
  "chadMisc1": sounds59,
  "chadMisc2": sounds60,
  "chadNearDeath1": sounds61,
  "chadNearDeath2": sounds62,
  "chadNewLevel1": sounds63,
  "chadNewLevel2": sounds64,
  "chadNewLevel3": sounds65,
  "chadNewLevel4": sounds66,
  "chadPickup1": sounds67,
  "chadPickup2": sounds68,
  "chadPickup3": sounds69,
  "chadTaunt1": sounds70,
  "chadTaunt2": sounds71,
  "chadTaunt3": sounds72,
  "chadTaunt4": sounds73,
  "chadTaunt5": sounds74,
  "chadTaunt6": sounds75,
  "chadWorried1": sounds76,
  "chadWorried2": sounds77,
  "chadWorried3": sounds78,
  "cindyDeath1": sounds79,
  "cindyHurt1": sounds80,
  "cindyHurt2": sounds81,
  "cindyHurt3": sounds82,
  "cindyJoinParty1": sounds83,
  "cindyLookHere1": sounds84,
  "cindyLookHere2": sounds85,
  "cindyMisc1": sounds86,
  "cindyNearDeath1": sounds87,
  "cindyNewLevel1": sounds88,
  "cindyPickup1": sounds89,
  "cindyRelief1": sounds90,
  "cindyTaunt1": sounds91,
  "cindyTaunt2": sounds92,
  "cindyWorried1": sounds93,
  "clariceDeath1": sounds94,
  "clariceDeath2": sounds95,
  "clariceHurt1": sounds96,
  "clariceHurt2": sounds97,
  "clariceHurt3": sounds98,
  "clariceJoinParty1": sounds99,
  "clariceLookHere1": sounds100,
  "clariceMisc1": sounds101,
  "clariceMisc2": sounds102,
  "clariceNearDeath": sounds103,
  "clariceNewLevel1": sounds104,
  "claricePickup1": sounds105,
  "clariceRelief1": sounds106,
  "clariceRelief2": sounds107,
  "clariceTaunt1": sounds108,
  "clariceWorried1": sounds109,
  "clydeDeath1": sounds110,
  "clydeHurt1": sounds111,
  "clydeHurt2": sounds112,
  "clydeJoinParty1": sounds113,
  "clydeLookHere1": sounds114,
  "clydeLookHere2": sounds115,
  "clydeMisc1": sounds116,
  "clydeNearDeath": sounds117,
  "clydeNewLevel1": sounds118,
  "clydeNewLevel2": sounds119,
  "clydeNewLevel3": sounds120,
  "clydeNewLevel4": sounds121,
  "clydePickup1": sounds122,
  "clydeRelief1": sounds123,
  "clydeRelief2": sounds124,
  "clydeRelief3": sounds125,
  "clydeTaunt1": sounds126,
  "clydeTaunt2": sounds127,
  "clydeWorried1": sounds128,
  "clydeWorried2": sounds129,
  "clydeWorried3": sounds130,
  "clydeWorried4": sounds131,
  "dustyRustyDeath1": sounds132,
  "dustyRustyDeath2": sounds133,
  "dustyRustyHurt1": sounds134,
  "dustyRustyHurt10": sounds135,
  "dustyRustyHurt2": sounds136,
  "dustyRustyHurt3": sounds137,
  "dustyRustyHurt4": sounds138,
  "dustyRustyHurt5": sounds139,
  "dustyRustyHurt6": sounds140,
  "dustyRustyHurt7": sounds141,
  "dustyRustyHurt8": sounds142,
  "dustyRustyHurt9": sounds143,
  "dustyRustyJoinParty1": sounds144,
  "dustyRustyJoinParty2": sounds145,
  "dustyRustyLevelComplete1": sounds146,
  "dustyRustyLevelComplete2": sounds147,
  "dustyRustyLevelComplete3": sounds148,
  "dustyRustyLevelComplete4": sounds149,
  "dustyRustyLevelComplete5": sounds150,
  "dustyRustyLookHere1": sounds151,
  "dustyRustyLookHere2": sounds152,
  "dustyRustyLookHere3": sounds153,
  "dustyRustyLookHere4": sounds154,
  "dustyRustyMisc1": sounds155,
  "dustyRustyMisc2": sounds156,
  "dustyRustyMisc3": sounds157,
  "dustyRustyMisc4": sounds158,
  "dustyRustyNearDeath1": sounds159,
  "dustyRustyNearDeath2": sounds160,
  "dustyRustyNewLevel1": sounds161,
  "dustyRustyNewLevel10": sounds162,
  "dustyRustyNewLevel11": sounds163,
  "dustyRustyNewLevel12": sounds164,
  "dustyRustyNewLevel2": sounds165,
  "dustyRustyNewLevel3": sounds166,
  "dustyRustyNewLevel4": sounds167,
  "dustyRustyNewLevel5": sounds168,
  "dustyRustyNewLevel6": sounds169,
  "dustyRustyNewLevel7": sounds170,
  "dustyRustyNewLevel8": sounds171,
  "dustyRustyNewLevel9": sounds172,
  "dustyRustyPickup1": sounds173,
  "dustyRustyPickup10Health": sounds174,
  "dustyRustyPickup11Health": sounds175,
  "dustyRustyPickup2": sounds176,
  "dustyRustyPickup3": sounds177,
  "dustyRustyPickup4": sounds178,
  "dustyRustyPickup5": sounds179,
  "dustyRustyPickup6": sounds180,
  "dustyRustyPickup7": sounds181,
  "dustyRustyPickup8": sounds182,
  "dustyRustyPickup9Health": sounds183,
  "dustyRustyTaunt1": sounds184,
  "dustyRustyTaunt2": sounds185,
  "dustyRustyTaunt3": sounds186,
  "dustyRustyTaunt4": sounds187,
  "dustyRustyTaunt5": sounds188,
  "dustyRustyTaunt6": sounds189,
  "dustyRustyTaunt7": sounds190,
  "dustyRustyTaunt8": sounds191,
  "dustyRustyWorried1": sounds192,
  "dustyRustyWorried2": sounds193,
  "dustyRustyWorried3": sounds194,
  "dustyRustyWorried4": sounds195,
  "dustyRustyWorried5": sounds196,
  "dustyRustyWorried6": sounds197,
  "kyleDeath1": sounds198,
  "kyleDeath2": sounds199,
  "kyleDeath3": sounds200,
  "kyleHurt1": sounds201,
  "kyleHurt2": sounds202,
  "kyleHurt4": sounds203,
  "kyleHurt5": sounds204,
  "kyleHurt6": sounds205,
  "kyleHurt7": sounds206,
  "kyleHurt8": sounds207,
  "kyleHurt9": sounds208,
  "kyleJoinParty1": sounds209,
  "kyleLookHere1": sounds210,
  "kyleLookHere2": sounds211,
  "kyleNearDeath1": sounds212,
  "kyleNearDeath2": sounds213,
  "kyleNewLevel1": sounds214,
  "kylePickup1": sounds215,
  "kylePickup2": sounds216,
  "kyleRelief1": sounds217,
  "kyleTaunt1": sounds218,
  "kyleWorried1": sounds219,
  "kyleWorried2": sounds220,
  "kyleWorried3": sounds221,
  "luckyJackDeath1": sounds222,
  "luckyJackDeath2": sounds223,
  "luckyJackHurt1": sounds224,
  "luckyJackHurt2": sounds225,
  "luckyJackHurt3": sounds226,
  "luckyJackHurt4": sounds227,
  "luckyJackHurt6": sounds228,
  "luckyJackJoinParty1": sounds229,
  "luckyJackLookHere": sounds230,
  "luckyJackMisc1": sounds231,
  "luckyJackNearDeath1": sounds232,
  "luckyJackNewLevel1": sounds233,
  "luckyJackNewLevel2": sounds234,
  "luckyJackNewLevel3": sounds235,
  "luckyJackPickup1": sounds236,
  "luckyJackRelief1": sounds237,
  "luckyJackTaunt1": sounds238,
  "luckyJackTaunt2": sounds239,
  "luckyJackTaunt3": sounds240,
  "luckyJackTaunt4": sounds241,
  "luckyJackTaunt5": sounds242,
  "luckyJackWorried1": sounds243,
  "nancyDeath3": sounds244,
  "nancyHurt1": sounds245,
  "nancyHurt2": sounds246,
  "nancyHurt3": sounds247,
  "nancyHurt4": sounds248,
  "nancyHurt5": sounds249,
  "nancyHurt6": sounds250,
  "nancyJoinParty1": sounds251,
  "nancyJoinParty2": sounds252,
  "nancyJoinParty3": sounds253,
  "nancyLookHere1": sounds254,
  "nancyLookHere2": sounds255,
  "nancyLookHere3": sounds256,
  "nancyMisc1": sounds257,
  "nancyMisc2": sounds258,
  "nancyNearDeath1": sounds259,
  "nancyNearDeath2": sounds260,
  "nancyNewLevel3": sounds261,
  "nancyPickup1": sounds262,
  "nancyPickup2": sounds263,
  "nancyRelief1": sounds264,
  "nancyRelief2": sounds265,
  "nancyRelief3": sounds266,
  "nancyTaunt1": sounds267,
  "nancyTaunt2": sounds268,
  "nancyWorried1": sounds269,
  "nancyWorried2": sounds270,
  "nancyWorried3": sounds271,
  "santaDeath1": sounds272,
  "santaHoHoHo1": sounds273,
  "santaHoHoHo2": sounds274,
  "santaHoHoHo3": sounds275,
  "santaHurt1": sounds276,
  "santaHurt2": sounds277,
  "santaHurt3": sounds278,
  "santaHurt4": sounds279,
  "santaHurt5": sounds280,
  "santaHurt6": sounds281,
  "santaHurt7": sounds282,
  "santaHurt8": sounds283,
  "santaJoin1": sounds284,
  "santaNewLevel1": sounds285,
  "santaNewLevel2": sounds286,
  "santaPickup2": sounds287,
  "santaPickupGun1": sounds288,
  "santaTaunt1": sounds289,
  "santaTaunt2": sounds290,
  "santaTaunt3": sounds291,
  "santaTaunt4": sounds292,
  "santaTaunt5": sounds293,
  "santaTaunt6": sounds294,
  "santaTaunt7": sounds295,
  "santaWorried1": sounds296,
  "santaWorried2": sounds297,
  "simonDeath1": sounds298,
  "simonHurt1": sounds299,
  "simonHurt2": sounds300,
  "simonHurt3": sounds301,
  "simonHurt4": sounds302,
  "simonHurt5": sounds303,
  "simonHurt6": sounds304,
  "simonHurt7": sounds305,
  "simonJoinParty1": sounds306,
  "simonLookHere1": sounds307,
  "simonLookHere2": sounds308,
  "simonNearDeath2": sounds309,
  "simonPickupItem1": sounds310,
  "simonPickupItem2": sounds311,
  "simonPickupItem3": sounds312,
  "simonRelief1": sounds313,
  "simonTaunt1": sounds314,
  "simonTaunt2": sounds315,
  "simonWorried1": sounds316,
  "simonWorried2": sounds317,
  "simonWorried3": sounds318,
  "takeshiDeath1": sounds319,
  "takeshiHurt1": sounds320,
  "takeshiHurt2": sounds321,
  "takeshiHurt3": sounds322,
  "takeshiHurt4": sounds323,
  "takeshiHurt6": sounds324,
  "takeshiHurt7": sounds325,
  "takeshiHurt8": sounds326,
  "takeshiJoinParty1": sounds327,
  "takeshiJoinParty2": sounds328,
  "takeshiLevelComplete1": sounds329,
  "takeshiLevelComplete2": sounds330,
  "takeshiLookHere1": sounds331,
  "takeshiMisc1": sounds332,
  "takeshiNearDeath1": sounds333,
  "takeshiNewLevel1": sounds334,
  "takeshiPickup1": sounds335,
  "takeshiPickup2": sounds336,
  "takeshiTaunt1": sounds337,
  "takeshiTaunt2": sounds338,
  "takeshiTaunt3": sounds339,
  "takeshiTaunt4": sounds340,
  "takeshiWorried1": sounds341,
  "takeshiWorried2": sounds342,
  "takeshiWorried3": sounds343,
  "wendyDeath1": sounds344,
  "wendyDeath2": sounds345,
  "wendyDeath3": sounds346,
  "wendyDeath4": sounds347,
  "wendyHurt1": sounds348,
  "wendyHurt2": sounds349,
  "wendyHurt3": sounds350,
  "wendyHurt4": sounds351,
  "wendyHurt6": sounds352,
  "wendyHurt7": sounds353,
  "wendyJoinParty1": sounds354,
  "wendyJoinParty2": sounds355,
  "wendyJoinParty3": sounds356,
  "wendyJoinParty4": sounds357,
  "wendyLookHere1": sounds358,
  "wendyLookHere2": sounds359,
  "wendyLookHere3": sounds360,
  "wendyMisc2": sounds361,
  "wendyMisc3": sounds362,
  "wendyNearDeath1": sounds363,
  "wendyNearDeath2": sounds364,
  "wendyNearDeath4": sounds365,
  "wendyNearDeath5": sounds366,
  "wendyNewLevel1": sounds367,
  "wendyNewLevel2": sounds368,
  "wendyNewLevel3": sounds369,
  "wendyNewLevel4": sounds370,
  "wendyPickup1": sounds371,
  "wendyPickup2": sounds372,
  "wendyPickup3": sounds373,
  "wendyPickup4": sounds374,
  "wendyPickup5": sounds375,
  "wendyPickup6": sounds376,
  "wendyPickup7": sounds377,
  "wendyRelief1": sounds378,
  "wendyRelief2": sounds379,
  "wendyRelief3": sounds380,
  "wendyRelief4": sounds381,
  "wendyRelief5": sounds382,
  "wendyRelief6": sounds383,
  "wendyTaunt1": sounds384,
  "wendyTaunt2": sounds385,
  "wendyTaunt4": sounds386,
  "wendyTaunt5": sounds387,
  "wendyTaunt3": sounds388,
  "wendyWorried1": sounds389,
  "wendyWorried2": sounds390,
  "wendyWorried3": sounds391,
  "wendyWorried4": sounds392,
  "chainLinkFence1": sounds393,
  "chainLinkFence2": sounds394,
  "chainLinkFence3": sounds395,
  "elevatorDing": sounds396,
  "elevatorDoorClose": sounds397,
  "elevatorDoorOpen": sounds398,
  "heavySwitchThrow": sounds399,
  "lightPowerOn1": sounds400,
  "powerWarmUp1": sounds401,
  "cabbageHit1": sounds402,
  "cabbageHit10": sounds403,
  "cabbageHit11": sounds404,
  "cabbageHit2": sounds405,
  "cabbageHit3": sounds406,
  "cabbageHit4": sounds407,
  "cabbageHit5": sounds408,
  "cabbageHit6": sounds409,
  "cabbageHit7": sounds410,
  "cabbageHit8": sounds411,
  "melonPlop1": sounds412,
  "melonPlop2": sounds413,
  "melonPlop3": sounds414,
  "melonPlop4": sounds415,
  "melonPlop5": sounds416,
  "melonPlop6": sounds417,
  "casingDropBoard1": sounds418,
  "casingDropBoard2": sounds419,
  "casingDropBoard3": sounds420,
  "casingDropBoard4": sounds421,
  "shotgunCasingDrop1": sounds422,
  "dryFire1": sounds423,
  "dryFire2": sounds424,
  "dryFire3": sounds425,
  "magazineLoad1": sounds426,
  "m1911Pickup": sounds427,
  "deagleShot1": sounds428,
  "deagleShot2": sounds429,
  "m1911DryFire": sounds430,
  "m1911Reload1": sounds431,
  "pistolCock1": sounds432,
  "pistolShot1": sounds433,
  "pistolShot2": sounds434,
  "pistol2Shot1": sounds435,
  "revolverDryFire": sounds436,
  "revolverInsertShell1": sounds437,
  "revolverInsertShell2": sounds438,
  "revolverInsertShell3": sounds439,
  "revolverPickup": sounds440,
  "revolverReloadFinish": sounds441,
  "revolverReloadStart": sounds442,
  "revolverShot3": sounds443,
  "ar15Reload1": sounds444,
  "ar15ReloadEmpty": sounds445,
  "rifleShot1": sounds446,
  "rifleShot2": sounds447,
  "rifleShot3": sounds448,
  "rifle2Shot1": sounds449,
  "shotgunLoadShell2": sounds450,
  "shotgunPump1": sounds451,
  "shotgunShot1": sounds452,
  "shotgunShot2": sounds453,
  "shotgunShot3": sounds454,
  "fleshHit1": sounds455,
  "fleshHit2": sounds456,
  "fleshHit3": sounds457,
  "fleshHit4": sounds458,
  "fleshHitBat1": sounds459,
  "fleshHitBat2": sounds460,
  "pianoHit1": sounds461,
  "pianoHit2": sounds462,
  "vendingMachineHit1": sounds463,
  "vendingMachineHit2": sounds464,
  "wallHit1": sounds465,
  "wallHit2": sounds466,
  "wallHit3": sounds467,
  "wallHit4": sounds468,
  "zombieBite1": sounds469,
  "zombieBite2": sounds470,
  "glowStickDrop1": sounds471,
  "glowStickDrop2": sounds472,
  "pop1": sounds473,
  "quarterDrop1": sounds474,
  "machineLoop1": sounds475,
  "bassGrooveLoop1": sounds476,
  "baseballBatPickup1": sounds477,
  "baseballBatPickup2": sounds478,
  "swordShing1": sounds479,
  "swordShing2": sounds480,
  "swordShing3": sounds481,
  "swordSwoosh1": sounds482,
  "swordSwoosh2": sounds483,
  "swordSwoosh3": sounds484,
  "kevinZombie1": sounds485,
  "kevinZombie10": sounds486,
  "kevinZombie11": sounds487,
  "kevinZombie12": sounds488,
  "kevinZombie13": sounds489,
  "kevinZombie14": sounds490,
  "kevinZombie15": sounds491,
  "kevinZombie17": sounds492,
  "kevinZombie18": sounds493,
  "kevinZombie19": sounds494,
  "kevinZombie2": sounds495,
  "kevinZombie20": sounds496,
  "kevinZombie21": sounds497,
  "kevinZombie23": sounds498,
  "kevinZombie24": sounds499,
  "kevinZombie25": sounds500,
  "kevinZombie26": sounds501,
  "kevinZombie27": sounds502,
  "kevinZombie28": sounds503,
  "kevinZombie29": sounds504,
  "kevinZombie3": sounds505,
  "kevinZombie30": sounds506,
  "kevinZombie31": sounds507,
  "kevinZombie32": sounds508,
  "kevinZombie33": sounds509,
  "kevinZombie34": sounds510,
  "kevinZombie35": sounds511,
  "kevinZombie36": sounds512,
  "kevinZombie37": sounds513,
  "kevinZombie38": sounds514,
  "kevinZombie39": sounds515,
  "kevinZombie4": sounds516,
  "kevinZombie5": sounds517,
  "kevinZombie7": sounds518,
  "kevinZombie8": sounds519,
  "kevinZombie9": sounds520,
  "perryZombie1": sounds521,
  "perryZombie10": sounds522,
  "perryZombie2": sounds523,
  "perryZombie3": sounds524,
  "perryZombie4": sounds525,
  "perryZombie6": sounds526,
  "perryZombie7": sounds527,
  "perryZombie8": sounds528,
  "perryZombie9": sounds529,
  "rachelZombie1": sounds530,
  "rachelZombie10": sounds531,
  "rachelZombie11": sounds532,
  "rachelZombie12": sounds533,
  "rachelZombie13": sounds534,
  "rachelZombie2": sounds535,
  "rachelZombie3": sounds536,
  "rachelZombie4": sounds537,
  "rachelZombie5": sounds538,
  "rachelZombie6": sounds539,
  "rachelZombie7": sounds540,
  "rachelZombie8": sounds541,
  "rachelZombie9": sounds542,
  "spitterSpit1": sounds543,
  "spitterSpit2": sounds544,
  "spitterSpit3": sounds545,
};
export type SoundName = keyof typeof sounds;
const fonts = {
  "oswald": fonts0,
  "captureIt": fonts1,
};
export type FontName = keyof typeof fonts;
export const RESOURCES = { images, sounds, fonts };
